# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5b2804dcfb0497604805a9ef4be9e3e5f3fba3d28e19529d24ad41ca3edd45659cf94a3d557eb50e3d25d58333250713c8c5ab847d5abb2615352378c7eea15

test:
  secret_key_base: fae40e3fdda9ff501a8319968b94e613d0ec9c5fe09d63fe002ce2fbe2f1fd602a37702a0e2fef20148531e944373bc9202926854bdd2a78e4c1b400070ac3da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
